runtime: go112

instance_class: F1

env_variables:
  AIRTABLE_SECRET: ""
  POSTGRES_HOST: "/cloudsql/INSTANCE_CONNECTION_NAME/.s.PGSQL.5432"
  POSTGRES_PORT: "5432"
  POSTGRES_USER: ""
  POSTGRES_PASSWORD: ""
  POSTGRES_NAME: "strides"

main: ./server

handlers:
  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto