runtime: nodejs10 # For Node.js 8, use runtime: nodejs8

instance_class: F1

env_variables:
  PRISMA_ENDPOINT: ${PRISMA_ENDPOINT}
  PRISMA_SECRET: ${PRISMA_SECRET}

handlers:
  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto
