runtime: nodejs10 # For Node.js 8, use runtime: nodejs8

instance_class: F1

env_variables:
  PRISMA_ENDPOINT: https://eu1.prisma.sh/simen-stoa/treningsplan-graphql-server/prod
  PRISMA_SECRET: daniels-running-formula

handlers:
  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto
